In [64]:
import os
from dotenv import load_dotenv
import numpy as np
import cv2
# Classification for the base classes

load_dotenv()

# Specify the path to the dataset directory
dataset_dir = os.getenv('DATASET_DIR')

target_size = (128, 128)

In [0]:
# Get all images
def read_images_from_directory(directory):
    images = []
    labels = []

    class_names = []
    for root, dirs, files in os.walk(directory):
        for class_name in dirs:
            class_directory = os.path.join(root, class_name)
            for filename in os.listdir(class_directory):
                file_path = os.path.join(class_directory, filename)
                if os.path.isfile(file_path):
                    image = cv2.imread(file_path , cv2.COLOR_BGR2GRAY)
                    if image is not None:
                        image = cv2.resize(image, target_size)
                        images.append(image)
                        labels.append(os.path.basename(root) + "." + class_name)
                        if class_name not in class_names:
                            class_names.append(class_name)

    images = np.array(images)
    labels = np.array(labels)
    class_names = np.array(class_names)

    return images, labels, class_names

In [71]:
images, labels, class_names = read_images_from_directory(dataset_dir)
images_with_labels = list(zip(images, labels))
print("Number of images:", len(images))
print("Number of labels:", len(labels))
print("Class names:", class_names)
print("Labels:", labels)

Number of images: 21
Number of labels: 21
Class names: ['big' 'small' 'agriculture_vehicle' 'bus' 'sportscar' 'curvy' 'adult'
 'child' 'handicaped' 'senior' 'danger' 'information' 'restriction'
 'speed_limit' 'yield' 'green' 'red' 'yellow']
Labels: ['animal_big' 'animal_small' 'car_agriculture_vehicle' 'car_bus'
 'car_sportscar' 'lane_curvy' 'pedestrian_adult' 'pedestrian_child'
 'pedestrian_handicaped' 'pedestrian_handicaped' 'pedestrian_senior'
 'traffic_sign_danger' 'traffic_sign_information'
 'traffic_sign_restriction' 'traffic_sign_restriction'
 'traffic_sign_restriction' 'traffic_sign_speed_limit'
 'traffic_sign_yield' 'trafic_light_green' 'trafic_light_red'
 'trafic_light_yellow']


In [77]:
print("First image: ",images_with_labels[0][0])
print("First image - label: ",images_with_labels[0][1])

First image:  [[[ 18  36  44]
  [ 11  30  34]
  [ 12  31  35]
  ...
  [  7  19  27]
  [  9  21  29]
  [ 15  26  34]]

 [[ 13  30  33]
  [ 12  39  45]
  [ 10  39  44]
  ...
  [ 10  20  27]
  [  9  21  29]
  [ 14  26  32]]

 [[ 11  32  34]
  [ 21  57  60]
  [ 20  56  62]
  ...
  [ 11  22  36]
  [ 11  23  32]
  [ 11  23  33]]

 ...

 [[ 66 149 142]
  [ 75 163 158]
  [ 64 148 146]
  ...
  [ 40  99  83]
  [ 44 106  93]
  [ 33  89  78]]

 [[ 62 147 140]
  [ 59 149 142]
  [ 63 156 144]
  ...
  [ 54 102  96]
  [ 17  82  71]
  [ 66 132 133]]

 [[ 68 152 141]
  [ 60 146 138]
  [ 77 151 154]
  ...
  [ 41 111 103]
  [ 50 118 113]
  [ 45 117 110]]]
First image - label:  animal_big
